version: "3.9"
services:
  server-app:
    container_name: game-server-app-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5157:5157"
    depends_on:
      - postgres
    command: sh -c "dotnet ef database update && dotnet /app/build/GameServer.dll"

  postgres:
    container_name: game-server-postgres-dev
    image: postgres
    environment:
      POSTGRES_USER: macbookair
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: game
    ports:
      - "6543:5432"

  nginx:
    container_name: game-server-nginx-dev
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - server-app
