version: '3.9'
services:
  game-server:
    container_name: game-server-app-local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5157:5157"
    depends_on:
      - postgres
    command: sh -c "dotnet ef database update && dotnet /app/build/GameServer.dll"
  
  postgres:
    container_name: game-server-postgres-local
    image: postgres
    environment:
      POSTGRES_USER: macbookair
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: game
    ports:
      - "5432:5432"
  
  nginx:
    container_name: game-server-nginx-local
    image: nginx
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"